version: '3.7'
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    tty: true
    stdin_open: true
    container_name: pdf_generator
    build: ./pdf_generator
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pdf_generator/:/usr/src/pdf_generator/
    ports:
      - 8000:8000
    env_file:
      - ./dev.env
    depends_on:
      - db

  redis:
    container_name: redis
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    env_file:
      - ./dev.env
  
  celery:
    container_name: celery
    build: ./pdf_generator
    command: celery -A config worker -l info
    volumes:
      - ./pdf_generator/:/usr/src/pdf_generator/
    env_file:
      - ./dev.env
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data: