# Generated by Django 3.1.6 on 2021-02-07 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInternetResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=256, unique=True, verbose_name='Ссылка на ресурс для преобразования')),
            ],
            options={
                'verbose_name': 'Ссылка на интернет ресурс',
                'verbose_name_plural': 'Ссылки на интернет ресурс',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Пользователь ресурса',
                'verbose_name_plural': 'Список пользователей ресурса',
            },
        ),
        migrations.CreateModel(
            name='ProcessingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания заявки')),
                ('done_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заявки')),
                ('conversion_file_link', models.URLField(max_length=255, verbose_name='Ссылка на файл для конвертирования')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'В ожидании'), (2, 'В процессе'), (3, 'Готово')], null=True, verbose_name='Статус заявки')),
                ('final_file_link', models.URLField(blank=True, max_length=256, unique=True, verbose_name='Ссылка на итоговый файл')),
                ('resulting_file_size', models.IntegerField(blank=True, null=True, verbose_name='Размер итогового файла')),
                ('conversion_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='converter.linkinternetresource', verbose_name='Ссылка на ресурс для конвертирования')),
                ('recipient_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='converter.recipient', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Заявка на преобразование в pdf',
                'verbose_name_plural': 'Заявки на преобразование в pdf',
            },
        ),
    ]
