# Generated by Django 3.1.6 on 2021-02-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingrequest',
            name='final_file_link',
        ),
        migrations.AddField(
            model_name='processingrequest',
            name='final_file',
            field=models.FileField(blank=True, unique=True, upload_to='documents/pdf', verbose_name='Итоговый файл pdf'),
        ),
        migrations.AlterField(
            model_name='processingrequest',
            name='conversion_file_link',
            field=models.FileField(upload_to='documents/html', verbose_name='Html файл для конвертирования'),
        ),
    ]
