# Generated by Django 3.1.6 on 2021-02-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_auto_20210207_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingrequest',
            old_name='conversion_file_link',
            new_name='conversion_file',
        ),
        migrations.RenameField(
            model_name='processingrequest',
            old_name='conversion_link',
            new_name='conversion_url',
        ),
        migrations.AddField(
            model_name='processingrequest',
            name='task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID задачи'),
        ),
    ]
