# Generated by Django 3.1.6 on 2021-02-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20210207_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingrequest',
            name='task_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID задачи'),
        ),
    ]
