# Generated by Django 3.1.6 on 2021-02-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_auto_20210207_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingrequest',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/pdf', verbose_name='Итоговый файл pdf'),
        ),
    ]
