# Generated by Django 3.1.6 on 2021-02-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_auto_20210207_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingrequest',
            name='done_datetime',
        ),
        migrations.RemoveField(
            model_name='processingrequest',
            name='resulting_file_size',
        ),
    ]
